apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wunbi6ofz-go
  janus-idp.io/tekton: wunbi6ofz-go
  backstage.io/kubernetes-id: wunbi6ofz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wunbi6ofz-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
